name: Release
on:
  release:
    types: [published]
    branches: [main]

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Release to AWS ECR
      uses: BattlesnakeOfficial/action-release-to-aws-ecr@main
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        
  push-artifact-registry:
    name: Push Image to GCP Artifact Registry
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Release to GCP Artifact Registry
      uses: BattlesnakeOfficial/action-release-to-gcp-ar@main
      with:
        image_tag: ${{ github.event.release.tag_name }}
        # Required
        gcp_artifact_registry: ${{ secrets.GCP_ARTIFACT_REGISTRY }}
        gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
        gcp_region: ${{ secrets.GCP_REGION }}
        gcp_service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
        gcp_workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        # Optional
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
